id=http-proxy
name=Endpoint HTTP proxy
version=3.21.0-SNAPSHOT
description=Endpoint that allows exposing Http SyncApi
class=io.gravitee.plugin.endpoint.http.proxy.HttpProxyEndpointConnectorFactory
type=endpoint-connector
features=