id=webhook
name=Entrypoint Webhook
version=3.21.0-SNAPSHOT
description=Entrypoint that allows exposing AsyncAPI using Webhook connection
class=io.gravitee.plugin.entrypoint.webhook.WebhookEntrypointConnectorFactory
type=entrypoint-connector