id=http-get
name=Entrypoint HTTP Get
version=3.21.0-SNAPSHOT
description=Entrypoint that allows exposing AsyncAPI using HTTP Get
class=io.gravitee.plugin.entrypoint.http.get.HttpGetEntrypointConnectorFactory
type=entrypoint-connector
features=limit,resume
