id=gravitee-idp
name=Gravitee.io APIM - Management API - Identity Providers - Repository
version=3.21.0-SNAPSHOT
description=The Gravitee.IO Parent POM provides common settings for all Gravitee components.
class=io.gravitee.rest.api.idp.repository.RepositoryIdentityProvider
type=identity_provider
