id=http-post
name=Entrypoint HTTP Post
version=3.21.0-SNAPSHOT
description=Entrypoint that allows exposing AsyncAPI using HTTP Post
class=io.gravitee.plugin.entrypoint.http.post.HttpPostEntrypointConnectorFactory
type=entrypoint-connector
features=