FROM speculate-artifact-restcountries

COPY tool/speculate-apidocs/genapidocs_v2/java_analyzer.py /artifact/tool/speculate-apidocs/genapidocs_v2/java_analyzer.py
COPY scripts/run_java_repo.sh /artifact/scripts/run_java_repo.sh
