id=repository-mongodb
name=Gravitee.io APIM - Repository - MongoDB
version=3.21.0-SNAPSHOT
description=The Gravitee.IO Parent POM provides common settings for all Gravitee components.
class=io.gravitee.repository.mongodb.MongoRepositoryProvider
type=repository
