id=repository-bridge-http-client
name=Gravitee.io APIM - Gateway - Repository - HTTP Bridge - Client
version=3.21.0-SNAPSHOT
description=The Gravitee.IO Parent POM provides common settings for all Gravitee components.
class=io.gravitee.repository.bridge.client.HttpBridgeRepositoryProvider
type=repository
