id=websocket
name=Entrypoint Websocket
version=3.21.0-SNAPSHOT
description=Entrypoint that allows exposing AsyncAPI using Websocket connection
class=io.gravitee.plugin.entrypoint.websocket.WebSocketEntrypointConnectorFactory
type=entrypoint-connector
