id=service-endpoint-discovery
name=Gravitee.io APIM - Gateway - Services - Endpoints Discovery
version=3.21.0-SNAPSHOT
description=The Gravitee.IO Parent POM provides common settings for all Gravitee components.
class=io.gravitee.gateway.services.endpoint.discovery.EndpointDiscoveryService
type=service
