id=http-proxy
name=Entrypoint HTTP Proxy
version=3.21.0-SNAPSHOT
description=Entrypoint that allows exposing Http SyncApi
class=io.gravitee.plugin.entrypoint.http.proxy.HttpProxyEntrypointConnectorFactory
type=entrypoint-connector
features=