id=sse
name=Entrypoint SSE
version=3.21.0-SNAPSHOT
description=Entrypoint that allows exposing AsyncAPI using SSE connection
class=io.gravitee.plugin.entrypoint.sse.SseEntrypointConnectorFactory
type=entrypoint-connector
features=resume