id=v3-upgrader
name=Gravitee.io APIM - Management API - Services - V3 - Upgrader
version=3.21.0-SNAPSHOT
description=The Gravitee.IO Parent POM provides common settings for all Gravitee components.
class=io.gravitee.rest.api.services.v3.upgrader.V3UpgraderService
type=service
